### ISSUE TITLE
Entries field with missing reference throws error inside Matrix 

### ISSUE THREAD

**Issue by floatingbits** [craftcms/feed-me#1069]
### Description
In a (entry-) feed containing a Matrix field with a nested Entries field, I get an error under some circumstances: 
Error:  

> Sammlungen: array_merge_recursive(): Argument #2 must be of type array, null given - Matrix.php: 106

Circumstances must be as follows: 
In the list of entry IDs, at least one entry must be found and a following one must not be found. This one will throw the error.

### Steps to reproduce

1. Set up a feed for an entry type containing an entries field inside a Matrix block. 
2. Feed data for the entries field has got the following pattern:
`{entriesField: 
"idThatCanBeFoundInTheSystem",
"idThatCanNOTBeFoundInTheSystem", //Will throw the error on feed run
}`

### Additional info

- Craft CMS version: 3.7.24
- Feed Me version: 4.4.1

I will provide a pull request for this. Seems to be fixed easily.

**Comment by ieuan** [comment]
This issue affects 5.0.5 as well, and the same code change seems to resolve the problem, does a new bug report need to be created?

### Additional info

- Craft version: 4.3.7.1
- PHP version: 8.0
- Database driver & version: postgres:15
- Plugins & versions: craftcms/feed-me:5.0.5

**Comment by angrybrad** [comment]
Resolved in https://github.com/craftcms/feed-me/commit/bc14d19929210b6b9d6b56d38cb0fb68294e7306

**Comment by brandonkelly** [comment]
Feed Me 4.6.0 (Craft 3) and 5.1.0 (Craft 4) have been released with the fix for this.

**Comment by Humbi1992** [comment]
Installed craftcms/cms 4.5.10 and craftcms/feed-me 5.2, this error is still happening to me
