### ISSUE TITLE
File cannot be reached

### ISSUE THREAD

**Issue by BSBjorn** [craftcms/feed-me#647]
### Description
I had a working feed, but after last update I no longer can process the JSON file provided getting this error: **

> "Unable to reach /Users/bjornkamfjord/Sites/******/imports/hybris/fpaks.json. Message: cURL error 3: (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) "

**

I have validatet the json file, and also checked if the path provided is reachable from the browser (it is). I have tried moving the file to different location, tried different files, different path formats (http://.... , @web, @webroot etc) all resulting in the same error. 

Is there something I'm missing? Has there been a change to how Feed Me works? Anything else I should try to solve? 

### Steps to reproduce

1. Run feed

### Additional info

- Plugin version: 4.2.0
- Craft version: Craft Pro 3.3.19

**Comment by BSBjorn** [comment]
Curl error 3 says "URL not properly formatted", but I can't see anything wrong with the parh? I have it locally and running on a staging server, same issue both places....

**Comment by stphnmartin** [comment]
I have the same issue. After the update all previously working feeds are inaccessible to FeedMe.

**Comment by stphnmartin** [comment]
I fixed this temporarily by reverting these lines near 134  in /vendor/craftcms/feed-me/src/services/ DataTypes.php

```
134        // Check for local or relative URL
135        if (!UrlHelper::isAbsoluteUrl($url)) {
136        // if (strpos($url, '://') === false && !UrlHelper::isProtocolRelativeUrl($url) && !UrlHelper::isRootRelativeUrl($url)) {
137            error_clear_last();
```

**Comment by angrybrad** [comment]
Just released 4.2.0.1 with a fix for this: https://github.com/craftcms/feed-me/releases/tag/4.2.0.1

**Comment by andersaloof** [comment]
I'm still having this issue.

It works in production (running on Linux), but on local dev on Windows 10, Feed Me will not import entries from my local JSON file and logs the same error as above.

This if check (https://github.com/craftcms/feed-me/blob/develop/src/services/DataTypes.php#L135) returns false for a windows path (in my case, the path returned from https://github.com/craftcms/feed-me/blob/develop/src/services/DataTypes.php#L132 is  `C:\WEB\project-name\storage/runtime/products_no.json`).

Looking at previous revisions of `DataTypes.php`, the if test also failed [here](https://github.com/craftcms/feed-me/blob/51e15e5846d45b190eacf14750926c597993c84d/src/services/DataTypes.php#L135), but worked in the revision from [november](https://github.com/craftcms/feed-me/blob/3599fb68166e6be61364f9fd308b6b6b4601c119/src/services/DataTypes.php#L135).
